events {}

http {

    upstream logistica_cluster {
        server donaton-services-logistica-1:8083;
        server donaton-services-logistica-2:8083;
        server donaton-services-logistica-3:8083;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://logistica_cluster;
        }
    }
}